#!/bin/sh

# reject commits that add lines including the word "nocheckin"
git diff HEAD -i --diff-filter=d -G nocheckin
exit $(git diff HEAD -i --diff-filter=d -G nocheckin --name-only | wc -l)

# vscode is dumb and thinks the commit succeeds, even if there is an error...
