#!/bin/sh

# prevent commits that add files containing "nocheckin"
git diff HEAD -i --diff-filter=d -G nocheckin
exit $(git diff HEAD -i --diff-filter=d -G nocheckin --name-only | wc -l)

# vscode is dumb and thinks the commit suceededs, even if there is an error...